import Head from "next/head";
import { Inter } from "next/font/google";
import { MdOutlineLightMode, MdLightMode } from "react-icons/md";
import { useState } from "react";
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import gustavo from "../../public/gustavo.jpeg";
import web1 from "../../public/web1.png";
import web2 from "../../public/web2.png";
import web5 from "../../public/web5.png";
import react from "../../public/react-logo.png";
import cakephp from "../../public/cakephp-logo.png";
import node from "../../public/node-logo.png";
import { Tooltip } from "react-tippy";
import "react-tippy/dist/tippy.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  console.log(darkMode);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Gustavo Coutinho</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white  dark:bg-gray-900  lg:px-0">
        <section className="min-h-min mb-14">
          <nav className="py-10 mb-12 flex justify-between bg-gray-200 dark:bg-gray-800 px-5 fixed w-full h-2 z-1">
            <h1 className="flex items-center text-xl font-burtons text-gray-800 dark:text-gray-200">
              developedby
            </h1>
            <ul className="flex items-center">
              <li>
                <div
                  className="cursor-pointer"
                  onClick={() => setDarkMode(!darkMode)}
                  title="Dark Mode"
                >
                  {darkMode ? (
                    <MdLightMode className="text-teal-500 text-2xl" />
                  ) : (
                    <MdOutlineLightMode className="text-teal-500 text-2xl" />
                  )}
                </div>
              </li>
              <li>
                
                  <a
                    className="bg-gradient-to-tr from-teal-400 px-4 py-2 rounded-md ml-8"
                    href="../../GustavoCoutinhoCV.pdf"
                    download="GustavoCoutinhoCV.pdf"
                  >
                    <Tooltip
                  title="Download my resume!"
                  position="bottom"
                  theme="light"
                >
                    Resume
                </Tooltip>
                  </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 pt-32">
            <h2 className="text-5xl text-teal-500">Gustavo Coutinho</h2>
            <h3 className="text-3xl text-teal-500">FullStack Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            I&apos;m a fullstack developer who aims to contribute to the development of
            great projects that will revolutionize the way things are done, optimizing time
            and the user experience with the product.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 text-gray-600">
            <a href="https://github.com/gustacoutinho/" target="_blank">
              <AiFillGithub />
            </a>
            <a href="https://www.linkedin.com/in/gucoutiinho/" target="_blank">
              <AiFillLinkedin />
            </a>
            <a href="https://www.instagram.com/gucoutiinho/" target="_blank">
              <AiFillInstagram />
            </a>
          </div>
          <div className=" h-80 w-80 mt-20 mx-auto">
            <Image
              src={gustavo}
              alt="Gustavo Coutinho"
              className="rounded-full"
            />
          </div>
        </section>
        <section className="px-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance and fulltime
              developer, I&apos;ve done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1 flex-col items-center flex">
              <Image src={cakephp} width={300} height={200} alt="image" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                A recipe to succeed
              </h3>
              <p className="py-2 text-justify">
                Prototype faster, Validate faster, Grow consistently. It is an
                incredible experience to work with CakePHP as it allows, with
                its MVC model, the creation of robust applications without
                losing flexibility.
              </p>
              <h4 className="py-4 text-teal-600">
                Libraries that I used together
              </h4>
              <p className="text-gray-800 py-1">jQuery</p>
              <p className="text-gray-800 py-1">Ajax</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">WebAuthn</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex-col items-center flex">
              <Image src={react} width={100} height={100} alt="image" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project with React
              </h3>
              <p className="py-2 text-justify">
                The powerful and famous library that makes components can be
                easily reused and shared between different parts of the
                application, making it flexible, responsive and providing an
                amazing user experience
              </p>
              <h4 className="py-4 text-teal-600">
                Libraries that I used together
              </h4>
              <p className="text-gray-800 py-1">Material-UI</p>
              <p className="text-gray-800 py-1">Socket.IO</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Redux</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1 flex-col items-center flex">
              <Image src={node} width={100} height={100} alt="image" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Node.js is an open source, cross-platform software that,
                together with powerful ORMs, allowed me to create some RESTful
                APIs that allowed the transfer of data in a secure way.
              </p>
              <h4 className="py-4 text-teal-600">
                Libraries that I used together
              </h4>
              <p className="text-gray-800 py-1">Sequelize</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">Axios</p>
              <p className="text-gray-800 py-1">AdonisJS</p>
            </div>
          </div>
        </section>
        <section className="py-10 px-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a fullstack developer,
              I&apos;ve worked on multiple projects, for{" "}
              <span className="text-teal-500"> myself </span>, for{" "}
              <span className="text-teal-500"> business </span>, and for my
              <span className="text-teal-500"> graduation </span>. All this can
              be found on my github page. During these projects, I collaborated
              with talented people who taught me a lot during this journey that
              is just beginning. Here are some examples:
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="image"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="image"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
